version: '3'
services:
  postgres:
    container_name: juni-postgre-db
    build: ./image/postgreSQL
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - /Users/uijun-lee/Private/Git/docker-postgreSQL/postgreSQL/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      
volumes:
  db-store:

### posgre의 컨테이너에 접속
# docker exec -u postgres -it juni-postgre-db bash

# 한번에 접속
# docker exec -u postgres -it juni-postgre-db 'psql'


### PostgreSQL접속
# postgres@93e2b0eb4044:~$ psql
# psql (13.5 (Debian 13.5-1.pgdg110+1))
# Type "help" for help.
#
# postgres=