version: '3'
services:
  postgres:
    container_name: juni-postgre-db
    build: ./image/postgreSQL
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - /Users/uijun-lee/Private/Git/docker-postgreSQL/postgreSQL/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      
volumes:
  db-store: