CHANGE MASTER TO MASTER_HOST = 'juni_mysql8.0.28_1', MASTER_PORT = 3306, MASTER_USER = 'repl', MASTER_PASSWORD = 'repl', MASTER_LOG_FILE='mysql-bin.000003', MASTER_LOG_POS=157;
SELECT SLEEP(30);
START SLAVE USER = 'repl' PASSWORD = 'repl';
