# https://dev.mysql.com/doc/refman/8.0/en/docker-mysql-more-topics.html#docker-configuring-server
#FROM mysql:8.0

# Time Zone
#ENV TZ Asia/Tokyo
#ENV TZ=UTC

#RUN apt-get -y update && apt-get -y upgrade
#RUN apt-get install vim -y
#RUN apt-get install mysql-server -y
RUN microdnf update -y
RUN microdnf install -y vim
#RUN apt-get install build-essential cmake wget curl libncurses5-dev libssl-dev gdb gdbserver -y

#RUN wget https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.33.tar.gz

#RUN tar zxvf mysql-8.0.33.tar.gz
