version: "3.9"

services:
  mysqlslap:
    image: diceone/mysqlslap
    container_name: mysqlslap
  mysql8_1:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: juni_mysql8.0.28_1
    ports:
      - "3301:3306"
    environment:
      MYSQL_DATABASE: "junitest"
      MYSQL_USER: "juni"
      MYSQL_PASSWORD: "juni"
      MYSQL_ROOT_PASSWORD: "admin"
      #TZ: "Asia/Tokyo"
      TZ: "UTC"
    volumes:
      - mysql1_data:/var/lib/mysql
      - ./my8.cnf:/etc/mysql/conf.d/my.cnf
      - ./test_db:/usr/local/src/test_db
      - ./mysql8_1-initdb:/docker-entrypoint-initdb.d
      - ./entrypoint_mysql8_1.sh:/usr/local/bin/entrypoint.sh  # 스크립트 추가
    #entrypoint: /usr/local/bin/entrypoint.sh
    command: 
      - --innodb_use_native_aio=0
      - --enable-log-bin
      - --server-id=1
      - --log-bin=mysql-bin.log
    networks:
      - juni-network


  mysql8_2:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: juni_mysql8.0.28_2
    ports:
      - "3302:3306"
    environment:
      MYSQL_DATABASE: "junitest"
      MYSQL_USER: "juni"
      MYSQL_PASSWORD: "juni"
      MYSQL_ROOT_PASSWORD: "admin"
      #TZ: Asia/Tokyo
      TZ: "UTC"
    volumes:
      - mysql2_data:/var/lib/mysql
      - ./my8_replica.cnf:/etc/mysql/conf.d/my.cnf
      - ./test_db:/usr/local/src/test_db
      - ./mysql8_2-initdb:/docker-entrypoint-initdb.d
      - ./entrypoint_mysql8_2.sh:/usr/local/bin/entrypoint.sh  # 스크립트 추가
    #entrypoint: /usr/local/bin/entrypoint.sh
    command: 
      - --innodb_use_native_aio=0
      - --disable-log-bin
      - --server-id=2
    networks:
      - juni-network

  #rails_app:
  #  #image: ruby:3.1.6
  #  build: .
  #  container_name: rails_app
  #  #command: bash -c "gem install bundler -v 2.5.18 && bundle install && rm -f tmp/pids/server.pid"
  #  command: bash -c "gem install bundler -v 2.5.18 && bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
  #  ports:
  #    - "3000:3000"
  #  environment:
  #    DATABASE_HOST: mysql8_1
  #    DATABASE_NAME: junitest
  #    DATABASE_USER: juni
  #    DATABASE_PASSWORD: juni
  #    RAILS_ENV: development
  #    TZ: Asia/Tokyo
  #  volumes:
  #    - ./rails_related:/usr/src/app
  #  working_dir: /usr/src/app
  #  depends_on:
  #    - mysql8_1
  #  networks:
  #    - juni-network

networks:
  juni-network:
    driver: bridge

volumes:
  mysql1_data:
  mysql2_data:

#  mysql57:
#    image: mysql:5.7.44
#    platform: linux/amd64
#    container_name: juni_mysql5.7.44
#    ports:
#      - "3302:3306"
#    environment:
#      MYSQL_DATABASE: "junitest"
#      MYSQL_USER: "juni"
#      MYSQL_PASSWORD: "juni"
#      MYSQL_ROOT_PASSWORD: "admin"
#      TZ: "Asia/Tokyo"
#    volumes:
#      - ./my57.cnf:/etc/mysql/conf.d/my.cnf
#      - ./test_db:/usr/local/src/test_db
#    command: 
#      - --innodb_use_native_aio=0
#      - --disable-log-bin

