version: "3.9"

services:
  mysql8:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: juni_mysql8.0.28
    ports:
      - "3301:3306"
    environment:
      MYSQL_DATABASE: "junitest"
      MYSQL_USER: "juni"
      MYSQL_PASSWORD: "juni"
      MYSQL_ROOT_PASSWORD: "admin"
      TZ: "Asia/Tokyo"
    volumes:
      - ./my8.cnf:/etc/mysql/conf.d/my.cnf
      - ./test_db:/usr/local/src/test_db
    command: 
      - --innodb_use_native_aio=0
      - --disable-log-bin

  mysql57:
    image: mysql:5.7.44
    platform: linux/amd64
    container_name: juni_mysql5.7.44
    ports:
      - "3302:3306"
    environment:
      MYSQL_DATABASE: "junitest"
      MYSQL_USER: "juni"
      MYSQL_PASSWORD: "juni"
      MYSQL_ROOT_PASSWORD: "admin"
      TZ: "Asia/Tokyo"
    volumes:
      - ./my57.cnf:/etc/mysql/conf.d/my.cnf
      - ./test_db:/usr/local/src/test_db
    command: 
      - --innodb_use_native_aio=0
      - --disable-log-bin

# docker-compose up -d 
# docker-compose down
# docker-compose exec mysql8 bash -c 'mysql -uroot -padmin -P3301'
# docker-compose exec mysql57 bash -c 'mysql -uroot -padmin -P3302'
# https://zenn.dev/ryo7/articles/create-mysql-on-docker
#
#
##### 
# docker compose run slap `
#####
# mysqlslap  --no-defaults --auto-generate-sql `
# --engine=innodb --auto-generate-sql-add-autoincrement  `
# --host=192.168.16.3 --port=3306 -u root -proot `
# --number-int-cols=10  --number-char-cols=10  --iterations=10  --concurrency=50  `
# --auto-generate-sql-write-number=10  --number-of-queries=10  --auto-generate-sql-load-type=read